name: Build Cubie A7A - Puro C y ASM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Instala dependencias
        run: |
          sudo apt update
          sudo apt install -y build-essential git bc bison flex libssl-dev libelf-dev cpio unzip rsync

      - name: Compila Buildroot
        run: |
          git clone https://github.com/buildroot/buildroot.git
          cp config-cubie-a7a-puro-c buildroot/.config
          cd buildroot
          make olddefconfig
          make -j$(nproc)

      - name: Lista imagenes
        run: ls -lh buildroot/output/images/

      - name: Sube artifact
        uses: actions/upload-artifact@v4
        with:
          name: cubie-a7a-C-ASM-64MB
          path: buildroot/output/images/
