name: Build Cubie A7A - Puro C y ASM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Instala toolchain
        run: sudo apt update && sudo apt install -y build-essential git bc bison flex libssl-dev cpio

      - name: Compila
        run: |
          git clone https://github.com/buildroot/buildroot.git
          cp config-cubie-a7a-puro-c buildroot/.config
          cd buildroot
          make olddefconfig
          make -j$(nproc)

      - name: Verifica que sea puro C
        run: |
          ls -lh buildroot/output/images/
          echo "---"
          file buildroot/output/images/*

      - uses: actions/upload-artifact@v4
        with:
          name: cubie-a7a-C-ASM-64MB
          path: buildroot/output/images/
